admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
#    defaults:
#        _locale: en

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
