App\Entity\CreatorClient:
  type: entity
  table: null
  repositoryClass: App\Repository\CreatorClientRepository
  manyToOne:
    entity:
      targetEntity: App\Entity\Client
  lifecycleCallbacks: {  }
